{% set data = load_setup_py_data() %}

package:
  name: ismrmrd-python
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python

requirements:
  build:
    - python
    - setuptools>=78
    - pip

  run:
    - python >=3.10
    - numpy>=1.22.0
    - h5py>=2.3
    - xsdata>=26.2

test:
  imports:
    - ismrmrd
  source_files:
    - tests
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest

about:
  home: https://github.com/ismrmrd/ismrmrd-python
  license: MIT
  summary: 'Python interface for ISMRMRD'
  description: |
    Python interface and utilities for the ISMRM Raw Data (ISMRMRD a.k.a. MRD) format.
  dev_url: https://github.com/ismrmrd/ismrmrd-python
  doc_url: https://github.com/ismrmrd/ismrmrd-python
  doc_source_url: https://github.com/ismrmrd/ismrmrd-python/blob/main/README.md
