name: Publish Conda package

on:
  push:
    branches: [master]
    tags: ["v*.*.*"]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-conda-packages:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: ismrmrd-python-build
          environment-file: conda/environment.yml
          python-version: 3.12
          auto-activate-base: false
      - name: Build conda package
        shell: bash -l {0}
        working-directory: conda
        run: |
          ./package.sh
          echo "Packages built: $(find build_pkg -name ismrmrd-python*.tar.bz2)"
      - name: Push conda package
        shell: bash -l {0}
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        working-directory: conda
        run: |
          for p in $(find build_pkg/ -regex '.*/ismrmrd-python.*\.\(conda\|tar.bz2\)')
          do
            ./publish_package.sh -u ismrmrd -t "$ANACONDA_TOKEN" -p "$p"
          done