on:
  pull_request:
    branches:    
      - master
  release:
    types:
      - created

jobs:
  build-conda-packages:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: conda-incubator/setup-miniconda@e81abac10ce2c37423b54eae5af93aa3b4d3475c
        with:
          activate-environment: ismrmrd-python-build
          environment-file: conda/environment.yml
          python-version: 3.9
          auto-activate-base: false
      - name: Build conda package
        shell: bash -l {0}
        working-directory: conda
        run: |
          ./package.sh
          echo "Packages built: $(find build_pkg -name ismrmrd-python*.tar.bz2)"
      - name: Push conda package
        shell: bash -l {0}
        if: ${{ github.event_name == 'release' }}
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        working-directory: conda
        run: |
          ./publish_package.sh -u ismrmrd -t "$ANACONDA_TOKEN" -p `find build_pkg -name ismrmrd-python*.tar.bz2`
